### ISSUE TITLE
Problème de cryptage

### ISSUE THREAD

**Issue by BasilicApps** [Ne0blast/AEjS#4]
J'ai testé le cryptage, donc je choisis le fichier à crypter (testé sous chrome, firefox et safari sur windows et mac) puis en cliquant sur upload, rien ne se passe, en tout cas la "progress bar" reste inactive comme si rien ne se produisait...

**Comment by BasilicApps** [comment]
Voici la log de la console de chrome, si ça peut aider ;)
[AEjS worker log file.log.zip](https://github.com/Ne0blast/AEjS/files/312161/AEjS.worker.log.file.log.zip)

**Comment by BasilicApps** [comment]
le problème se trouve à la ligne 36 du fichier "test.html", c'est la ligne: "var worker = new Worker("aeJs.worker.js");", il retourne une valeur nulle

**Comment by Ne0blast** [comment]
Aucun soucis de mon côté, je n'arrive pas à reproduire ton bug

**Comment by Super-Baleine** [comment]
Personally, i didn't have this problem... At my high school, this works fine, also in my PC...
